### ISSUE TITLE
Infludb connection

### ISSUE THREAD

**Issue by jeevan9510** [influxdata/docs.influxdata.com-ARCHIVE#2978]
I am trying to install Telegraf,influxdb,chronograf,and kapacitor each in different ec2 windows instances. When i am trying to connect influxdb instance using chronograf UI by mentioning influxdb public IPV4 with port number 8086.there is an error "Unable to connect influxDB influx 1:Error in contacting source".

**Comment by kelseiv** [comment]
Hi @jeevan9510, 

To install a version of InfluxDB that includes a UI (no Chronograf needed!), please check out our latest version--InfluxDB 2.0.8. Here's how to [install InfluxDB 2.0](https://docs.influxdata.com/influxdb/v2.0/install/).

If you need to stay on InfluxDB 1.x, check to be sure all instances have permissions to access each other, and verify whether you've enabled InfluxDB authentication for [connecting to Chronograf](https://docs.influxdata.com/chronograf/v1.9/introduction/installation/#connect-chronograf-to-your-influxdb-instance-or-influxdb-enterprise-cluster). 

For future questions and assistance, please see our [InfluxCommunity site](https://community.influxdata.com/), lots of helpful folks who can answer your questions.
